services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      BIOMEDICBACKEND_APP_RUNNING_MODE: production
    volumes:
      - .:/home/app/api
    networks:
      - fastapi-network
    command: [ "/bin/bash", "-c", "uv run uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000" ]
    restart: unless-stopped

networks:
  fastapi-network:
    driver: bridge