[default]
API_PREFIX = "/api/v1"
PROXY_ROOT_PATH = ""
API_URL_BASE = ""
SERVER_RELOAD = 1
SAVE_PREDICTION = 0

[production]
API_URL_BASE = "https://biomedic-backend.lucaspraciano.com"
SERVER_RELOAD = 0

[development]
SERVER_RELOAD = 1

[testing]
SERVER_RELOAD = 0